### ISSUE TITLE
Add gallery button on general section above MLH

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#1046]
Ideally it'd be opacity-'d out and say "Gallery coming soon!"
This is so the MLH button doesn't look lonely, and users will maybe think to check back and see where the gallery is.

It should be more noticeable here rather than on the navbar? Thoughts? @cbaudouinjr

**Comment by peterkos** [comment]
Put side-by-side with the MLH button on med screens; on mobile; vertical.

**Comment by peterkos** [comment]
Director's meeting feedback: this buton is a go!

**Comment by colbygallup** [comment]
Flex test (latest Firefox version): https://gyazo.com/5eb5b45ec8238a3f9a345f163425ec3f

Will upload and create PR as soon as I get permission to create new branches
