### ISSUE TITLE
Update ricky hero svgs to use the ones on Notion, adjust color of site

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#1087]
Fixes the bugs with alignment

design todo:
- [x] Ricky SVGS updated on notion
- [x] Decide which `$dark-blue` to use (using `#1A305F`)

**Comment by peterkos** [comment]
![CleanShot 2021-01-25 at 22 18 35](https://user-images.githubusercontent.com/2782749/105795762-5d7bf700-5f5b-11eb-8071-bfcec2011e84.png)

**Comment by sjmiller7** [comment]
no two colors are the same. please fix.
