### ISSUE TITLE
make contact us section have some sort of hover effect 

### ISSUE THREAD

**Issue by JeremyRudman** [codeRIT/brickhack.io#1093]
With the introduction of the sponsor section all parts of the website have a hover effect to show a item is clickable but the contact us section does not. A possible effect could be a lift up effect for the social images and a underline for the text.
![image](https://user-images.githubusercontent.com/38338616/103726500-0e1f5800-4fa7-11eb-9889-f1342b3f876a.png)

**Comment by peterkos** [comment]
waiting to check in w/ design

**Comment by peterkos** [comment]
Design likes hover idea!
