### ISSUE TITLE
Leadership bios

### ISSUE THREAD

**Issue by Madrugaur** [codeRIT/brickhack.io#1104]
I think it would be cool if each of the leadership team had a little bio that popped up if you clicked their name or image on the site. Superfluous af but a cool feature for bh8 maybe

**Comment by peterkos** [comment]
We're planning this for the codeRIT site! Given the backlog of issues currently, if we run out of things this is a cool idea :smile:

**Comment by peterkos** [comment]
Closing as we'll save this for codeRIT site
