### ISSUE TITLE
Integrate registration with My MLH

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#240]
MLH launched a registration API, My MLH. Worth checking out and possibly integrating for our use: https://github.com/MLH/omniauth-mlh, https://my.mlh.io/

**Comment by ColdSauce** [comment]
Are we still doing this?

**Comment by sman591** [comment]
Yep, I plan on integrating it once @gabe-k finishes the upgrade to Rails 4

**Comment by ColdSauce** [comment]
Cool!
