### ISSUE TITLE
Error pages display incorrect logo

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#255]
Error pages show the old, thin logo, except we transitioned to the newer logo.

Currently: (ignore speaker image)
![screenshot 2015-11-11 19 58 54](https://cloud.githubusercontent.com/assets/1441807/11107774/eb15683c-88ae-11e5-9967-7ca3f25d694e.png)

Should be:
![screenshot 2015-11-11 19 59 38](https://cloud.githubusercontent.com/assets/1441807/11107781/ef316ea2-88ae-11e5-95d4-34be3d61cc61.png)

**Comment by jvdub** [comment]
Submitted a PR: #398

**Comment by piedoom** [comment]
I believe this was actually fixed in pr #399
