### ISSUE TITLE
Improve overview of reg information in confirmation emails

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#263]
Currently our confirmation emails include a copy of the registrant's information, which is good, however is provided in a simple text list.

The design of this can be improved to distinguish between the question names & answers, and/or align answers to be more easily readable.
 
![screenshot 2015-11-21 12 48 17](https://cloud.githubusercontent.com/assets/1441807/11319716/3c46991e-904e-11e5-94d5-fbee1ac450c4.png)

**Comment by piedoom** [comment]
- [ ] create mockup
- [ ] implement in html/css
- [ ] test on multiple clients

**Comment by sman591** [comment]
FYI we're using the [roadie-rails](https://github.com/Mange/roadie-rails) gem, so all CSS inlining from style sheets is taken care of automatically. You can preview emails at `/mail_view` - just make sure you have at least one completed application (and user).

**Comment by piedoom** [comment]
Awesome, I was just looking up how to do that now.

**Comment by piedoom** [comment]
I'm curious for your thought - do you think it is necessary to restate all the user-input information over again?  I'm starting to think it might be better just to provide the link to where they can update or view what they've entered.  Putting it all in email seems a little redundant.

**Comment by sman591** [comment]
@piedoom My original thought was that it would give them a final chance to realize if they've made any mistakes. But just a confirmation with link to access/edit the information could work too, I guess, since they are presented with a copy of the information on the website once they finish their application.

**Comment by piedoom** [comment]
I made a very minimal stylesheet and created a little email design out of it.  This is pure simplicity stuff, text can be added in easily if we decided we needed it.  I'm missing the footer links here, but they'd be in the final.  

Creating an animation for the header somewhere would really make the email look tons better, so I created something really quick (note the file is structured so i can swap out logo files for when we finalize our stuff)

[Imgur](http://i.imgur.com/uwZIUlp.gifv)

Everything is in the marketing folder.  I'm starting to really like the slightly rounded buttons (but still modern/flat) style.  I think it works well with the more fun/saturated colors we have than everything boxy.  The pure boxy stuff we have now gives me a more "upperclass" "high fashion" kind of vibe.

**Comment by sman591** [comment]
Looking good - I like the style guides too. How is the animation handled?

**Comment by piedoom** [comment]
It's just a gif - cant really animate in JS since emails don't support it.

**Comment by piedoom** [comment]
just PRed #284.  Let me know what I can do to make this better.  Some links are still dummy content since I'm not sure how MLH's API will work.

**Comment by sman591** [comment]
Closed in #284
