### ISSUE TITLE
DEPRECATION WARNING: You didn't set `secret_key_base` 

### ISSUE THREAD

**Issue by piedoom** [codeRIT/brickhack.io#279]
Checking the [Travis](https://travis-ci.org/codeRIT/brickhack.io) logs, this error seems to be breaking every test.

**Comment by sman591** [comment]
If you run 'bundle exec rake test' locally, does this same error occur?

**Comment by piedoom** [comment]
Not exactly -  here's what I get
    DEPRECATION WARNING: The configuration option `config.serve_static_assets`
    has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving 
    everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` 
    alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from  
    block in <top (required)> at /home/alexander/Documents/git/brickhack.io/config/environments
    /test.rb:16)
    rake aborted!
    Devise.secret_key was not set. Please add the following to your Devise initializer:

Not really sure why devise is asking for the secret key since I only usually see that done in production mode.  Same with the static assets.  Possible our environment got messed up somehow?

**Comment by sman591** [comment]
A secret key is needed regardless - usually a default is provided in the config file which fixed this. I'll take a look.

**Comment by sman591** [comment]
`config/secrets.yml` was previously missing, which caused the secret key fatal error. Devise uses the rails secret key based introduced in one of the rails 4.x releases, so adding it back to version control solved that: 147c52048d095b83c4639f0da3bbb2d46e988a5f

The static assets warning is still happening, though. Closing this and creating a separate issue.
