### ISSUE TITLE
BrickHack II content

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#281]
Basic event info, sponsors, etc

**Comment by piedoom** [comment]
Is there a doc somewhere where I can find the info that I'll be using?

**Comment by sman591** [comment]
Are you able to do a `git checkout` to last years website? Around April 1st would probably give you a good base of what info we had. I can create a doc later tonight with exact information.

**Comment by piedoom** [comment]
cool, will do.

**Comment by piedoom** [comment]
Going to try checking out to April later, but if you have any more stuff that has changed a doc would be super useful.


To do: 
- [ ] aggregate content
- [ ] create a mockup 
- [ ] implement in html/css
- [ ] test/get feedback

**Comment by sman591** [comment]
@piedoom Have you checked Slack? Sent you the link to the doc

**Comment by piedoom** [comment]
@sman591, this should be 99% done.  Tested on chrome, firefox, Chrome on Android - probably won't play *tooo* nice with IE 10 or 11, but I don't think we need to worry about that.  Safari should be good but I don't have access to it.

The homepage is almost done, save some content issues (fixing the FAQ to be correct, etc.)  Let me know if you have a finalized FAQ so I can edit it, or if you'd like to do that part yourself.

It's pretty late and I'm a little dead, so I'll try to get out some logo variations tomorrow.  The logo we have now won't be that different regardless, so it should be too bad.

All the sponsors you've listed are also on this list and included in assets.

**Comment by sman591** [comment]
@piedoom Looks awesome. I'll update the content in a bit; we also need a button for any interest sponsors to click that takes them to the PDF (hosted in /assets/). I can probably add it.

Also, is the "current" nav item supposed to update as they scroll? (like Bootstrap's [scrollspy](http://getbootstrap.com/javascript/#scrollspy))

**Comment by piedoom** [comment]
Where do you think the button would fit, in the sponsors section?  And yes, they will update when scrolling - that's a little effect I have to implement still.

**Comment by sman591** [comment]
I was thinking centered, at the bottom of all the logos

**Comment by piedoom** [comment]
Sorry for the delay, I'll have that up in a sec.  routing it to the root temporarily.

**Comment by piedoom** [comment]
@sman591, got the sponsor link up.  I put it above the logos, since I think it'll provide more visibility.  Most people won't scroll all the way down once we have a fair amount of sponsors.

**Comment by sman591** [comment]
@piedoom Perfect. I just pushed up my content changes - look good?

**Comment by sman591** [comment]
@piedoom Just did a rebase on develop & updated asset paths. Can I merge this and then have a separate PR for the scrolling? Want to get it on staging to verify all is good.
