### ISSUE TITLE
Error pages are missing styles

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#286]
See: https://staging.brickhack.io/thispagedoesntexist

**Comment by jvdub** [comment]
Should be a pretty easy fix. Either a mapping is off or the resources just need to be updated to include the correct path. I'll have a closer look sometime soon.

**Comment by piedoom** [comment]
Seems like we can't use the asset pipeline without dynamic error pages.  I'll switch that over now.  

Also wondering, is there a reason why we have a hardcoded CSRF token in every page?  Not really sure what good that does...

**Comment by sman591** [comment]
Fixed in #399 

https://staging.brickhack.io/foobar
