### ISSUE TITLE
Add Fedora to sponsors

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#328]

**Comment by wilfriedE** [comment]
I think you closed the wrong issue.

**Comment by sman591** [comment]
Oh yep haha, thank you!

**Comment by wilfriedE** [comment]
@sman591 :+1:

**Comment by sman591** [comment]
@wilfriedE If you can & want to submit a PR for this that'd be awesome

**Comment by wilfriedE** [comment]
@sman591 :+1:  will do once we get permission to use and an official logo. Probably by early next week

**Comment by sman591** [comment]
@wilfriedE Sounds good, I'm gonna assign this to you
