### ISSUE TITLE
Resume uploads via Firefox don't work

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#351]
< 2MB files don't work: One applicant reported that the issue only existed on Firefox (Arch Linux) but worked on Google Chrome.

Wrong file type: another applicant reported their PDF resume was marked as not a PDF.

**Comment by piedoom** [comment]
Were there only two of these cases?  The second account sounds like pebcak to me.

**Comment by sman591** [comment]
@piedoom The only two reported cases, and I think I was able to reproduce in Firefox back in February. Haven't tested since.

**Comment by sman591** [comment]
Closing as there's a new upload endpoint and couldn't reproduce
