### ISSUE TITLE
Migrate off of Mandrill

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#377]
[What a horrible change](http://blog.mandrill.com/important-changes-to-mandrill.html). SparkPost, SendGrid, or something else needed.

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They are giving 100,000 free emails/month.

**Comment by richleland** [comment]
@sman591 our own @aydrian will be up your way this weekend - feel free to ask him LOTS of questions. :smile:

**Comment by aydrian** [comment]
That's right. We'll be there sponsoring and mentoring. Stop by and say hello!

**Comment by sman591** [comment]
Migrated our SMTP & DNS settings to Sparkpost 🎉  next step is using the API instead of SMTP, but that'll be a separate task.
