### ISSUE TITLE
Sponsor logos are distorted on Firefox

### ISSUE THREAD

**Issue by craigcabrey** [codeRIT/brickhack.io#382]
![screenshot from 2016-03-02 10-49-37](https://cloud.githubusercontent.com/assets/894565/13465620/89fa8344-e064-11e5-9f64-8f19be24520c.png)

**Comment by sman591** [comment]
Oh wow, that's bad. I'll look into this, thanks!

**Comment by craigcabrey** [comment]
FF 44.0.2 FWIW

Also confirmed on OS X
