### ISSUE TITLE
As an applicant, if I visit the RSVP page and get redirected, I should know why

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#383]

**Comment by prayashm** [comment]
@sman591 Can you explain more? Where can I find the RSVP page?

**Comment by sman591** [comment]
Removing hacktoberfest label as this might be a little more involved.

A user can get redirected due to:
* Not being logged in
* Not being accepted

**Comment by sman591** [comment]
This issue was moved to codeRIT/hackathon_manager#32
