### ISSUE TITLE
Add strong parameter tests

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#411]
With the move to strong parameters, the tests against mass assignment were removed. Testing against correct strong parameters should be added, and is simplified with shoulda: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/action_controller/permit_matcher.rb

**Comment by Vandalisk** [comment]
Hello, @sman591 . Please, tell me where strong parameters are. I didn't find any in controllers in the development branch. If I understood correctly, in this issue I need to add should-matchers test of strong params for each controller with strong params?

**Comment by sman591** [comment]
@vandalisk sorry about that! Intended to get the Rails 5 upgrade merged last night but got blocked on a test not passing. I'll update this issue when it's merged.

**Comment by sman591** [comment]
@Vandalisk Merged! The tests in question that were removed are seen in https://github.com/codeRIT/brickhack.io/pull/412/commits/9f58a5bec08effdfb3e8a63faaf9139a31f8899b - essentially, there should be a replacement for the `should allow_mass_assignment_of` tests that were removed.

**Comment by sman591** [comment]
This issue was moved to codeRIT/hackathon_manager#19
