### ISSUE TITLE
Update travel email

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#491]
We've changed the address, needs to be updated on the website - `travel-[year]@coderit.org`

**Comment by dquach217** [comment]
Are you sure it has been changed? Because from my understanding, it has always been the same. @chrisbaudouinjr : Has the travels email changed to the format that Stuart has made, or is it relatively the same?

**Comment by sman591** [comment]
@dquach217 @chrisbaudouinjr - Velizar and I changed it to this format at the very end of last year - the regular travel email was getting a ton of spam before

**Comment by chrisbaudouinjr** [comment]
Just confirmed email was up-to-date and functional.

**Comment by sman591** [comment]
(re-opening b/c we still need to update the email on the website - blocked on https://github.com/codeRIT/hackathon_manager/issues/14)

**Comment by sman591** [comment]
All set now 👍
