### ISSUE TITLE
Add Rollbar JS error reporting

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#590]
We have server-side reporting, but client-side should be added too

**Comment by dquach217** [comment]
@sman591 What kind of logging do you want to have? I noticed that we already have Rollbar gem integrated with our system

**Comment by sman591** [comment]
Essentially the same that we have on the backend. We have the Rollbar gem installed, which logs all server-side errors for us. Rollbar also has a JavaScript/browser SDK that we should use to log any browser-side JavaScript errors. Should be as simple as copy & pasting a `<script>` code snippet out of their browser JS docs with a project access token

**Comment by peterkos** [comment]
Implemented in github.com/codeRIT/hackathon-manager/ as not relevant to this project anymore
