### ISSUE TITLE
Redesign Error Pages

### ISSUE THREAD

**Issue by sman591** [codeRIT/brickhack.io#646]
Right now, our error pages use the sidebar way back from the original BrickHack. This no longer works on mobile (required JavaScript no longer included), and the sidebar is more than needed for a simple error page.

Error pages can be reduced to:

* Current logo
* Title
* Description
* Error code
* Button to home

Can be exactly the same as the existing design, just stripped down to remove the sidebar and move the logo

...for 404, 422, and 500 error pages

**Comment by dquach217** [comment]
@sman591 
<img width="890" alt="Screen Shot 2019-03-24 at 1 19 09 AM" src="https://user-images.githubusercontent.com/22206901/54875308-f5927d80-4dd2-11e9-8bf4-840518f70993.png">

**Comment by sman591** [comment]
I'd say the logo could be much smaller (smaller logo, more margin instead) and be the generic non-year-specific version, but looks good

**Comment by peterkos** [comment]
Considering it's a one-page site, it might be better to just redirect to the homepage. Someone would have to manually enter a strange path in the URL to get somewhere other than there, and if the site was down, no pages would render at all iirc. Thoughts?

**Comment by sman591** [comment]
If it remains a one-page site yeah. If there's more than one, consider people may have old emails with now-broken links, and organizers can easily copy/paste links wrong in e.g. social media or emails to a specific page.

**Comment by peterkos** [comment]
Cool! I'll remove the existing error pages; then we're keeping it one page, at least for BH7.
