### ISSUE TITLE
When rsvp_confirmed they receive noise

### ISSUE THREAD

**Issue by dquach217** [codeRIT/brickhack.io#716]
When hackers have accepted they received a lot of emails from us, especially the "Are you still Coming." Not sure if this is a bug @sman591 but it should be something to look into after BHV

**Comment by sman591** [comment]
Ok that's expected then -- messages were intentionally sent out then to re-confirm people's attendance.

I think we can close then? Sounds like something to discuss when sending emails out, not a bug with the code

**Comment by dquach217** [comment]
We can close then and discuss this with the directors
