### ISSUE TITLE
Gallery Image storage through s3

### ISSUE THREAD

**Issue by devinmatte** [codeRIT/brickhack.io#774]
I've never been a fan of storing non-ui assets (images) within git, especially when resources like s3 exist.
Ideally move to image storage and retrieval through s3 to avoid inflating the git repo with binaries

(If CodeRIT doesn't have their own s3 instance, I can provide hosting through CSH)

**Comment by peterkos** [comment]
Thanks for the heads up! For our next BrickHack we'll be rebuilding the site; so, this system for galleries will also be rebuilt. (It's a holdover from a previous codeRIT team who was more pressed for time than anything else!)

**Comment by devinmatte** [comment]
Great to hear. Please feel free to reach out for s3 hosting to rtp@csh.rit.edu. It should be super quick to have set up and Brickhack already being hosted on CSH makes things easier

**Comment by peterkos** [comment]
Note to us: no design needed on this issue; redesign will come separately

**Comment by peterkos** [comment]
Note: implementing #1068 first

**Comment by peterkos** [comment]
fixed on #1085!
