### ISSUE TITLE
Arrow is messed up on moible

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#917]
firefox small window

<img src="https://user-images.githubusercontent.com/2782749/87082662-609ada00-c1f9-11ea-958c-10d6b1d6f211.png" width="300px" />

brickhack7
<img src="https://user-images.githubusercontent.com/2782749/87082680-64c6f780-c1f9-11ea-8fdf-10520fedb3dd.png" width="300px" />

**Comment by ww2497** [comment]
1st picture: just an issue with desktop firefox
2nd picture: Likely just an iPhone 7 issue, should be fixed
