### ISSUE TITLE
Make MailChimp email input hint fade/disappear upon selection

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/brickhack.io#926]
When clicking on the email input field for subscribing for updates, the hint doesn't fade or disappear. This causes the user to think there is already text in the input that they need to remove before proceeding. 

<img width="404" alt="Screen Shot 2020-07-10 at 1 01 03 AM" src="https://user-images.githubusercontent.com/22222538/87118236-d67a6200-c248-11ea-99ea-29ec80775ac3.png">

**Comment by peterkos** [comment]
What browser was this on? :p

**Comment by cbaudouinjr** [comment]
> What browser was this on? :p

Safari
