### ISSUE TITLE
BrickHack is being cutoff by MLH banner

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/brickhack.io#930]
When viewing the index the BrickHack text is cutoff by the MLH banner.

Device: iPhone 11 Pro Max
Browser: Safari

<img width="517" alt="Screen Shot 2020-07-11 at 8 09 08 PM" src="https://user-images.githubusercontent.com/22222538/87236081-625bcd80-c3b2-11ea-9694-4487c0e2509a.png">

**Comment by ww2497** [comment]
ooops

**Comment by cbaudouinjr** [comment]
Reopening as issue has not been merged
