### ISSUE TITLE
Hero text + image is not vertically centered

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#931]
Firefox, Safari
Top+Bottom space should be same size
<img width="1904" alt="Screen Shot 2020-07-12 at 12 27 42 AM" src="https://user-images.githubusercontent.com/2782749/87239555-75849280-c3de-11ea-8d83-bff062a6db00.png">

**Comment by peterkos** [comment]
Need to discuss w/ design first

**Comment by ww2497** [comment]
It's centered if you zoom out a bunch. I thought it looked better closer to the nav for shorter screens

**Comment by peterkos** [comment]
Spoke w/ May, she agreed that it should be centered, but all the elements should be a bit bigger (font sizes + hero image) to help clear some of the space around the edges

I see where you're coming from but I think the banner + navbar are distinct enough that users can recognize they're different from the centered content

**Comment by ww2497** [comment]
What do you think the new width should be? It currently fits within a 1100 px width which is our cutoff for mobile layout

**Comment by peterkos** [comment]
Maybe 1400px? Try to make the middle text + hero image larger to taste, then we can match the cutoffs
