### ISSUE TITLE
codeRIT hiring blurb in the HTML comments / JS console

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#937]
As a bit of future-proofing for more engineers, I think it'd be fun to put a little bit of information for joining codeRIT.

I've seen a few websites do stuff like this -- inevitably, _someone_ will poke around in the devtools, and we want those people on board!

**Comment by ww2497** [comment]
Cute idea, do you want me to write something up on my own & just link the codeRIT site?

**Comment by peterkos** [comment]
Sure!
