### ISSUE TITLE
"Contact Us" button/link

### ISSUE THREAD

**Issue by peterkos** [codeRIT/brickhack.io#942]
We might have a dedicated button for this but not quite sure yet on how it would fit UX-wise.
One possibility is to have `interested in sponsoring? email sponsorship@coderit.org` on the site.

**Comment by ww2497** [comment]
Are we waiting on design to make a decision for this?

**Comment by peterkos** [comment]
Just checked with May, she agreed to have that text right under the email signup button. If you need a mockup lmk!

**Comment by peterkos** [comment]
Actually I can just take this one, it's been a while since i've contributed code 😅

**Comment by ww2497** [comment]
Alright. I can take over if you can't find time, there hasn't been much to do for a while on my end so I'm very free
